#!/bin/sh -e
set -e

if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    update-alternatives --remove \
        sddm-debian-theme \
        /usr/share/sddm/themes/2001
fi

# Tag to allow some debhelper commands to inject relevant code
#DEBHELPER#

